// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUWIw3J9lxFmzdWqN-vK_6Q4qQkB-xmt8',
    appId: '1:1081825170446:web:64ee526cfeeea2ebfc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    authDomain: 'mealtrack-4b239.firebaseapp.com',
    databaseURL: 'https://mealtrack-4b239-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    measurementId: 'G-9ZGKX53QVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE2n8tu6VQzxVi5eWlEMilapAgd0ddzU',
    appId: '1:1081825170446:android:e6e0bc6a9f527f1dfc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    databaseURL: 'https://mealtrack-4b239-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38XzsVo2n44ug8NRqUm-9KWPFl6g2ItM',
    appId: '1:1081825170446:ios:de7cb0bdf9fdcf2cfc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    databaseURL: 'https://mealtrack-4b239-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    androidClientId: '1081825170446-dvbil6k7m45qed4etj3v4kbqsd7l4q0r.apps.googleusercontent.com',
    iosClientId: '1081825170446-983f1du3ein766kbqdvcb23pboubdbi7.apps.googleusercontent.com',
    iosBundleId: 'de.yamt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38XzsVo2n44ug8NRqUm-9KWPFl6g2ItM',
    appId: '1:1081825170446:ios:de7cb0bdf9fdcf2cfc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    databaseURL: 'https://mealtrack-4b239-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    androidClientId: '1081825170446-dvbil6k7m45qed4etj3v4kbqsd7l4q0r.apps.googleusercontent.com',
    iosClientId: '1081825170446-983f1du3ein766kbqdvcb23pboubdbi7.apps.googleusercontent.com',
    iosBundleId: 'de.yamt.app',
  );

}