// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcVFS2UJg6VAXu9DmAHrN9LlDWDQgUIfY',
    appId: '1:1081825170446:web:1df73194067f1d71fc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    authDomain: 'mealtrack-4b239.firebaseapp.com',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    measurementId: 'G-FKNDX9FM4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE2n8tu6VQzxVi5eWlEMilapAgd0ddzU',
    appId: '1:1081825170446:android:7e36f8505733fbcbfc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38XzsVo2n44ug8NRqUm-9KWPFl6g2ItM',
    appId: '1:1081825170446:ios:38cf9c851ee1c541fc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    iosBundleId: 'com.example.mealtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38XzsVo2n44ug8NRqUm-9KWPFl6g2ItM',
    appId: '1:1081825170446:ios:38cf9c851ee1c541fc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    iosBundleId: 'com.example.mealtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcVFS2UJg6VAXu9DmAHrN9LlDWDQgUIfY',
    appId: '1:1081825170446:web:d7ee2415970da130fc985f',
    messagingSenderId: '1081825170446',
    projectId: 'mealtrack-4b239',
    authDomain: 'mealtrack-4b239.firebaseapp.com',
    storageBucket: 'mealtrack-4b239.firebasestorage.app',
    measurementId: 'G-V11TP1119T',
  );
}
