import 'dart:io';

final _featureImportPattern = RegExp(
  r'''(?:import|export)\s+['"]package:yamt/features/([^/]+)/''',
);
final _featureLabels = <String, String>{
  'meal_templates': 'Meal Templates',
  'prepared_meals': 'Prepared Meals',
  'product_nutrition': 'Product Nutrition',
  'product_search': 'Product Search',
  'shoppinglist': 'Shopping List',
};

void main() {
  final root = Directory.current;
  final featuresDir = Directory(_join(root.path, 'lib', 'features'));
  if (!featuresDir.existsSync()) {
    stderr.writeln('Could not find lib/features under ${root.path}.');
    exitCode = 1;
    return;
  }

  final featureNames =
      featuresDir
          .listSync()
          .whereType<Directory>()
          .map((directory) => _basename(directory.path))
          .toList()
        ..sort();

  final dependencyMap = <String, Map<String, Set<String>>>{};

  for (final entity in featuresDir.listSync(recursive: true)) {
    if (entity is! File || !_isSourceFile(entity.path)) {
      continue;
    }

    final relativePath = _relativeToRoot(root.path, entity.path);
    final ownerFeature = _ownerFeature(relativePath);
    if (ownerFeature == null) {
      continue;
    }

    final content = entity.readAsStringSync();
    for (final match in _featureImportPattern.allMatches(content)) {
      final dependencyFeature = match.group(1);
      if (dependencyFeature == null ||
          dependencyFeature == ownerFeature ||
          !featureNames.contains(dependencyFeature)) {
        continue;
      }

      dependencyMap
          .putIfAbsent(ownerFeature, () => <String, Set<String>>{})
          .putIfAbsent(dependencyFeature, () => <String>{})
          .add(relativePath);
    }
  }

  final output = File(
    _join(root.path, 'docs', 'architecture.generated.md'),
  );
  output.writeAsStringSync(
    _buildDocument(
      featureNames: featureNames,
      dependencyMap: dependencyMap,
      generatedAt: DateTime.now().toUtc(),
    ),
  );

  stdout.writeln('Wrote ${_relativeToRoot(root.path, output.path)}');
}

String _buildDocument({
  required List<String> featureNames,
  required Map<String, Map<String, Set<String>>> dependencyMap,
  required DateTime generatedAt,
}) {
  final edgeRows = <_EdgeRow>[];
  for (final fromEntry in dependencyMap.entries) {
    for (final toEntry in fromEntry.value.entries) {
      final files = toEntry.value.toList()..sort();
      edgeRows.add(
        _EdgeRow(
          from: fromEntry.key,
          to: toEntry.key,
          files: files,
        ),
      );
    }
  }
  edgeRows.sort(_compareEdgeRows);

  final buffer = StringBuffer()
    ..writeln('# Generated Feature Dependency Graph')
    ..writeln()
    ..writeln(
      'This file is generated by '
      '`dart run tool/generate_feature_dependency_diagram.dart`.',
    )
    ..writeln()
    ..writeln('It scans non-generated Dart files under `lib/features/**` and')
    ..writeln(
      'extracts `import` and `export` references to '
      '`package:yamt/features/<feature>/...`.',
    )
    ..writeln()
    ..writeln('- Generated at: `${generatedAt.toIso8601String()}`')
    ..writeln('- Features scanned: `${featureNames.length}`')
    ..writeln('- Cross-feature edges: `${edgeRows.length}`')
    ..writeln()
    ..writeln('## Mermaid')
    ..writeln()
    ..writeln('```mermaid')
    ..writeln('flowchart LR');

  for (final feature in featureNames) {
    final nodeId = _nodeId(feature);
    final label = _labelForFeature(feature);
    buffer.writeln('  $nodeId[$label]');
  }

  if (edgeRows.isNotEmpty) {
    buffer.writeln();
  }

  for (final edge in edgeRows) {
    final fromId = _nodeId(edge.from);
    final toId = _nodeId(edge.to);
    buffer.writeln(
      '  $fromId -->|${edge.files.length}| $toId',
    );
  }

  buffer
    ..writeln('```')
    ..writeln()
    ..writeln('## Edge Details')
    ..writeln();

  if (edgeRows.isEmpty) {
    buffer.writeln('No cross-feature imports found.');
    return buffer.toString();
  }

  for (final edge in edgeRows) {
    buffer.writeln(
      '- `${edge.from} -> ${edge.to}` '
      '(${edge.files.length} file${edge.files.length == 1 ? '' : 's'})',
    );
    for (final file in edge.files.take(5)) {
      buffer.writeln('  - `$file`');
    }
    if (edge.files.length > 5) {
      buffer.writeln('  - `... and ${edge.files.length - 5} more`');
    }
  }

  return buffer.toString();
}

bool _isSourceFile(String path) {
  return path.endsWith('.dart') &&
      !path.endsWith('.g.dart') &&
      !path.endsWith('.freezed.dart');
}

String? _ownerFeature(String relativePath) {
  final normalized = relativePath.replaceAll(r'\', '/');
  final parts = normalized.split('/');
  if (parts.length < 3 || parts[0] != 'lib' || parts[1] != 'features') {
    return null;
  }
  return parts[2];
}

String _relativeToRoot(String rootPath, String path) {
  final normalizedRoot = rootPath.replaceAll(r'\', '/');
  final normalizedPath = path.replaceAll(r'\', '/');
  if (!normalizedPath.startsWith(normalizedRoot)) {
    return normalizedPath;
  }
  final trimmed = normalizedPath.substring(normalizedRoot.length);
  return trimmed.startsWith('/') ? trimmed.substring(1) : trimmed;
}

String _join(String first, String second, [String? third, String? fourth]) {
  final parts = <String>[first, second];
  if (third != null) {
    parts.add(third);
  }
  if (fourth != null) {
    parts.add(fourth);
  }
  return parts.join(Platform.pathSeparator);
}

String _basename(String path) {
  final normalized = path.replaceAll(r'\', '/');
  final parts = normalized.split('/');
  return parts.isEmpty ? normalized : parts.last;
}

String _nodeId(String feature) {
  return feature.replaceAll(RegExp('[^a-zA-Z0-9_]'), '_');
}

String _labelForFeature(String feature) {
  final configuredLabel = _featureLabels[feature];
  if (configuredLabel != null) {
    return configuredLabel;
  }

  return feature
      .split('_')
      .map((part) {
        if (part.isEmpty) {
          return part;
        }
        return part[0].toUpperCase() + part.substring(1);
      })
      .join(' ');
}

int _compareEdgeRows(_EdgeRow left, _EdgeRow right) {
  final countCompare = right.files.length.compareTo(left.files.length);
  if (countCompare != 0) {
    return countCompare;
  }

  final fromCompare = left.from.compareTo(right.from);
  if (fromCompare != 0) {
    return fromCompare;
  }

  return left.to.compareTo(right.to);
}

class _EdgeRow {
  const _EdgeRow({
    required this.from,
    required this.to,
    required this.files,
  });

  final String from;
  final String to;
  final List<String> files;
}
